openapi: 3.0.1
info:
  title: erugo
  description: ''
  version: 1.0.0
tags: []
paths:
  /api/health/:
    get:
      summary: Health check endpoint
      deprecated: false
      description: ''
      tags: []
      parameters: []
      responses:
        '200':
          description: Pong response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
          headers: {}
      security: []
  /api/shares/:
    post:
      summary: Create a new share
      deprecated: false
      description: ''
      tags: []
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: ''
                description:
                  type: string
                  example: ''
                files:
                  type: array
                  items:
                    type: string
                    format: binary
                  example: ''
      responses:
        '200':
          description: Share created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  share_url:
                    type: string
          headers: {}
      security: []
  /api/shares/{long_id}/:
    get:
      summary: Get a share by its long ID
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: long_id
          in: path
          description: ''
          required: true
          example: ''
          schema:
            type: string
      responses:
        '200':
          description: Share details
          content:
            application/json:
              schema:
                type: object
                properties:
                  Id:
                    type: integer
                  Name:
                    type: string
                  Description:
                    type: string
                  FilePath:
                    type: string
                  ExpirationDate:
                    type: string
                  LongId:
                    type: string
          headers: {}
      security: []
  /api/shares/{long_id}/download/:
    get:
      summary: Download a share
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: long_id
          in: path
          description: ''
          required: true
          example: ''
          schema:
            type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties: {}
      responses:
        '200':
          description: File downloaded successfully
          content:
            application/octet-stream:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
components:
  schemas: {}
  securitySchemes: {}
servers: []
security: {}
